2022-01-21 16:03:52,696 INFO    MainThread:31108 [wandb_setup.py:_flush():71] setting env: {}
2022-01-21 16:03:52,696 INFO    MainThread:31108 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-21 16:03:52,697 INFO    MainThread:31108 [wandb_init.py:_log_setup():371] Logging user logs to C:\Users\rb01243\OneDrive - University of Surrey\Documents\GitHub\dental_disease\notebooks\wandb\run-20220121_160352-25mwlth4\logs\debug.log
2022-01-21 16:03:52,697 INFO    MainThread:31108 [wandb_init.py:_log_setup():372] Logging internal logs to C:\Users\rb01243\OneDrive - University of Surrey\Documents\GitHub\dental_disease\notebooks\wandb\run-20220121_160352-25mwlth4\logs\debug-internal.log
2022-01-21 16:03:52,697 INFO    MainThread:31108 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001E8B7B3F9D0>
2022-01-21 16:03:52,697 INFO    MainThread:31108 [wandb_init.py:init():404] calling init triggers
2022-01-21 16:03:52,697 INFO    MainThread:31108 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-21 16:03:52,697 INFO    MainThread:31108 [wandb_init.py:init():460] starting backend
2022-01-21 16:03:52,697 INFO    MainThread:31108 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-01-21 16:03:52,702 INFO    MainThread:31108 [backend.py:ensure_launched():216] starting backend process...
2022-01-21 16:03:52,769 INFO    MainThread:31108 [backend.py:ensure_launched():221] started backend process with pid: 38896
2022-01-21 16:03:52,770 INFO    MainThread:31108 [wandb_init.py:init():469] backend started and connected
2022-01-21 16:03:52,779 INFO    MainThread:31108 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-21 16:03:52,780 INFO    MainThread:31108 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-01-21 16:03:52,780 INFO    MainThread:31108 [wandb_init.py:init():533] updated telemetry
2022-01-21 16:03:52,781 INFO    MainThread:31108 [wandb_init.py:init():563] communicating current version
2022-01-21 16:03:54,139 INFO    MainThread:31108 [wandb_init.py:init():568] got version response 
2022-01-21 16:03:54,139 INFO    MainThread:31108 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-21 16:03:56,260 ERROR   Thread-8  :31108 [internal_api.py:execute():144] 405 response executing GraphQL.
2022-01-21 16:03:56,260 ERROR   Thread-8  :31108 [internal_api.py:execute():145] 
2022-01-21 16:04:04,437 ERROR   Thread-8  :31108 [internal_api.py:execute():144] 405 response executing GraphQL.
2022-01-21 16:04:04,437 ERROR   Thread-8  :31108 [internal_api.py:execute():145] 
2022-01-21 16:04:23,488 ERROR   Thread-8  :31108 [internal_api.py:execute():144] 405 response executing GraphQL.
2022-01-21 16:04:23,488 ERROR   Thread-8  :31108 [internal_api.py:execute():145] 
2022-01-21 16:04:24,142 INFO    MainThread:31108 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2022-01-21 16:04:24,142 ERROR   MainThread:31108 [wandb_init.py:init():583] backend process timed out
2022-01-21 16:04:24,142 ERROR   MainThread:31108 [wandb_init.py:init():592] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
