Overriding model.yaml nc=80 with nc=2
                 from  n    params  module                                  arguments
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     18816  models.common.C3                        [64, 64, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  2    115712  models.common.C3                        [128, 128, 2]
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  6                -1  3    625152  models.common.C3                        [256, 256, 3]
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]
 24      [17, 20, 23]  1     18879  models.yolo.Detect                      [2, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 270 layers, 7025023 parameters, 7025023 gradients, 15.9 GFLOPs
Transferred 344/350 items from yolov5s.pt
Scaled weight_decay = 0.0005859375
[34m[1moptimizer:[39m[22m SGD with parameter groups 57 weight, 60 weight (no decay), 60 bias
[34m[1mtrain: [39m[22mScanning '..\data\datasets\All_Volunteers_Calc_Removed_John_Test_Crowdsourced\labels\train' images and labels...:   0%|          | 0/1552 [00:00<?, ?it/s]

[34m[1mtrain: [39m[22mScanning '..\data\datasets\All_Volunteers_Calc_Removed_John_Test_Crowdsourced\labels\train' images and labels...1552 found, 0 missing, 0 empty, 1 corrupted: 100%|██████████| 1552/1552 [00:05<00:00, 270.40it/s]
[34m[1mtrain: [39m[22mWARNING: Ignoring corrupted image and/or label ..\data\datasets\All_Volunteers_Calc_Removed_John_Test_Crowdsourced\images\train\Unknown-X-20200130-084742-XLGSYPPPTEXC-0.JPG: non-normalized or out of bounds coordinate labels
[34m[1mtrain: [39m[22mNew cache created: ..\data\datasets\All_Volunteers_Calc_Removed_John_Test_Crowdsourced\labels\train.cache
[34m[1mval: [39m[22mScanning '..\data\datasets\All_Volunteers_Calc_Removed_John_Test_Crowdsourced\labels\test' images and labels...100 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 100/100 [00:03<00:00, 25.19it/s]
[34m[1mval: [39m[22mNew cache created: ..\data\datasets\All_Volunteers_Calc_Removed_John_Test_Crowdsourced\labels\test.cache
Plotting labels...
[34m[1mautoanchor: [39m[22mAnalyzing anchors... anchors/target = 5.36, Best Possible Recall (BPR) = 0.9985
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to [1mruns\train\ex1_Zoon_without_Calc_10epo_John_Val
Starting training for 10 epochs...
     Epoch   gpu_mem       box       obj       cls    labels  img_size
YOLO+BCC

       0/9     10.2G         0   0.02266         0       414       640:   0%|          | 0/63 [00:04<?, ?it/s]Exception in thread Thread-55:
Traceback (most recent call last):
  File "C:\Users\rb01243\Anaconda3\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\rb01243\Anaconda3\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rb01243\OneDrive - University of Surrey\Documents\GitHub\miccai\miccai_dental_disease\src\utils\plots.py", line 204, in plot_images
    annotator.im.save(fname)  # save
  File "C:\Users\rb01243\Anaconda3\lib\site-packages\PIL\Image.py", line 2237, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'runs\\train\\ex1_Zoon_without_Calc_10epo_John_Val2\\train_batch0.jpg'
       0/9     13.3G         0   0.02248         0       332       640:   3%|▎         | 2/63 [00:11<05:43,  5.64s/it]Exception in thread Thread-57:
Traceback (most recent call last):
  File "C:\Users\rb01243\Anaconda3\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\rb01243\Anaconda3\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rb01243\OneDrive - University of Surrey\Documents\GitHub\miccai\miccai_dental_disease\src\utils\plots.py", line 204, in plot_images
    annotator.im.save(fname)  # save
  File "C:\Users\rb01243\Anaconda3\lib\site-packages\PIL\Image.py", line 2237, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'runs\\train\\ex1_Zoon_without_Calc_10epo_John_Val2\\train_batch1.jpg'
       0/9     13.3G         0   0.02228         0       285       640:   5%|▍         | 3/63 [00:16<05:02,  5.04s/it]Exception in thread Thread-59:
Traceback (most recent call last):
  File "C:\Users\rb01243\Anaconda3\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\rb01243\Anaconda3\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rb01243\OneDrive - University of Surrey\Documents\GitHub\miccai\miccai_dental_disease\src\utils\plots.py", line 204, in plot_images
    annotator.im.save(fname)  # save
  File "C:\Users\rb01243\Anaconda3\lib\site-packages\PIL\Image.py", line 2237, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'runs\\train\\ex1_Zoon_without_Calc_10epo_John_Val2\\train_batch2.jpg'












       0/9     13.3G         0   0.01919         0       259       640:  24%|██▍       | 15/63 [01:08<03:40,  4.60s/it]