2022-01-21 16:27:28,081 INFO    MainThread:27248 [wandb_setup.py:_flush():71] setting env: {}
2022-01-21 16:27:28,081 INFO    MainThread:27248 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-21 16:27:28,081 INFO    MainThread:27248 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-21 16:27:28,081 INFO    MainThread:27248 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-21 16:27:28,081 INFO    MainThread:27248 [wandb_init.py:_log_setup():371] Logging user logs to C:\Users\rb01243\OneDrive - University of Surrey\Documents\GitHub\dental_disease\src\wandb\run-20220121_162728-x5iqankp\logs\debug.log
2022-01-21 16:27:28,081 INFO    MainThread:27248 [wandb_init.py:_log_setup():372] Logging internal logs to C:\Users\rb01243\OneDrive - University of Surrey\Documents\GitHub\dental_disease\src\wandb\run-20220121_162728-x5iqankp\logs\debug-internal.log
2022-01-21 16:27:28,081 INFO    MainThread:27248 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000024197A47E20>
2022-01-21 16:27:28,082 INFO    MainThread:27248 [wandb_init.py:init():404] calling init triggers
2022-01-21 16:27:28,082 INFO    MainThread:27248 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'bcc_epoch': -1, 'qtfilter_epoch': -1, 'qt_thres_mode': '', 'qt_thres': 0.0, 'hybrid_entropy_thres': 0.0, 'hybrid_conf_thres': 0.0, 'weights': 'yolov5s.pt', 'cfg': '', 'data': '../data/iid-tvt.yaml', 'hyp': {'lr0': 0.01, 'lrf': 0.2, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'obj': 1.0, 'cls': 0.5, 'cls_pw': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0, 'copy_paste': 0.0}, 'epochs': 2, 'batch_size': 18, 'imgsz': 640, 'rect': False, 'resume': False, 'nosave': False, 'noval': False, 'noautoanchor': False, 'evolve': None, 'bucket': '', 'cache': None, 'image_weights': False, 'device': '', 'multi_scale': False, 'single_cls': False, 'adam': False, 'sync_bn': False, 'workers': 8, 'project': 'runs/train', 'entity': None, 'name': 'test11', 'exist_ok': False, 'quad': False, 'linear_lr': False, 'label_smoothing': 0.0, 'upload_dataset': False, 'bbox_interval': -1, 'save_period': -1, 'artifact_alias': 'latest', 'local_rank': -1, 'freeze': 0, 'patience': 1100, 'save_dir': 'runs\\train\\test11'}
2022-01-21 16:27:28,082 INFO    MainThread:27248 [wandb_init.py:init():460] starting backend
2022-01-21 16:27:28,082 INFO    MainThread:27248 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-01-21 16:27:28,086 INFO    MainThread:27248 [backend.py:ensure_launched():216] starting backend process...
2022-01-21 16:27:28,154 INFO    MainThread:27248 [backend.py:ensure_launched():221] started backend process with pid: 22176
2022-01-21 16:27:28,155 INFO    MainThread:27248 [wandb_init.py:init():469] backend started and connected
2022-01-21 16:27:28,165 INFO    MainThread:27248 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-21 16:27:28,166 INFO    MainThread:27248 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-01-21 16:27:28,166 INFO    MainThread:27248 [wandb_init.py:init():533] updated telemetry
2022-01-21 16:27:28,167 INFO    MainThread:27248 [wandb_init.py:init():563] communicating current version
2022-01-21 16:27:29,519 INFO    MainThread:27248 [wandb_init.py:init():568] got version response 
2022-01-21 16:27:29,519 INFO    MainThread:27248 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-21 16:27:59,531 INFO    MainThread:27248 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2022-01-21 16:27:59,531 ERROR   MainThread:27248 [wandb_init.py:init():583] backend process timed out
2022-01-21 16:27:59,531 ERROR   MainThread:27248 [wandb_init.py:init():592] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-01-21 16:29:36,077 ERROR   Thread-8  :27248 [internal_api.py:execute():144] 405 response executing GraphQL.
2022-01-21 16:29:36,077 ERROR   Thread-8  :27248 [internal_api.py:execute():145] 
